### ISSUE TITLE
Initializing the code to RPi3

### ISSUE THREAD

**Issue by dharshanduck** [vjaunet/QUADCOPTER#4]
We've encountered a problem while making the PILOT; line 78 of the servo.cpp file "sleep(1);" was not declared in the code and we cannot figure the dependencies for the project as a whole, could you advise us please?

![2017-03-24-091449_1600x900_scrot](https://cloud.githubusercontent.com/assets/9196526/24287811/14ed61ce-10b6-11e7-9785-0e1a9ed4890d.png)

**Comment by vjaunet** [comment]
Probably a missing include, Google just gave me:
 https://ubuntuforums.org/showthread.php?t=982545
Good luck,
Vincent

**Comment by dharshanduck** [comment]
Thanks Vincent for the earlier assistance, it all works now.
However, when it comes to running everything on the RPI after building from the Makefile, does everything run as services, or is there supposed to be any interfaces??  we are quite confused

@vjaunet
